name: "\U0001F41E Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this necessary bug report!
        Could you please hit the Star if you find this project helpful or your problem was resolved afterwards? thanks 🙏
  - type: checkboxes
    attributes:
      label: "Before you start, please make sure to:"
      options:
      - label: Read the document
        required: true
      - label: Have tried the latest version
        required: true
      - label: Search to see if your issue already exists
        required: true
      - label: Look for Q&A through appropriate channels like [Stack Overflow](https://stackoverflow.com/questions/ask)
        required: false
  - type: input
    attributes:
      label: Link to minimal reproduction
      description: |
        Try reproducing it in [StackBlitz](https://vite.new), [The SFC Playground (Vue 3 only)](https://play.vuejs.org) or a GitHub repository
        [Why reproductions are required, and how to create one?](https://antfu.me/posts/why-reproductions-are-required)
        > [!Tip]
        > - Sending PRs with failing tests or at least a well-crafted reproduction, is a huge step towards maintainers or other contributors landing a fix
        > - The best reproduction is the reproduction never sent - you find the problems/solutions during making the reproduction
      placeholder: Valid link
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!Caution]
        > - The reproduction should contain only the bare minimum (but complete) amount of code needed to show the bug
        > - Make reasonable efforts to troubleshoot and rule out issues with your own code or any 3rd party library
        > - Enable incognito/private mode to avoid interference from browser extensions and caches
  - type: checkboxes
    attributes:
      label: "Validation"
      options:
      - label: ⚠ I understand that invalid, incomplete or superfluous reproduction can lead to this issue being closed
        required: true
  - type: textarea
    attributes:
      label: Describe the bug and steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code, avoid code screenshots
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages`
      render: shell
      placeholder: System, JS/TS Runtime, Browser, NPM Packages
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Package Manager
      options:
        - pnpm
        - bun
        - npm
        - yarn
        - cnpm
        - other
    validations:
      required: false
