name: "\U0001F41E Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this necessary bug report!
        Please keep in mind that PRs welcome 😊
        Could you hit the Star if this project helped or your problem was resolved afterwards? tks! 🙏
  - type: checkboxes
    attributes:
      label: "Before you start, please make sure to:"
      options:
      - label: Read the doc
        required: true
      - label: Have tried the latest version
        required: true
      - label: Search to see if your issue already exists
        required: true
      - label: Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/ask)
        required: false
  - type: input
    attributes:
      label: Link to minimal reproduction
      description: |
        Try reproducing it in [StackBlitz](https://vite.new), [The SFC Playground (Vue 3 only)](https://play.vuejs.org) or a GitHub repository.
        The reproduction should be **minimal** - i.e. it should contain only the bare minimum amount of code needed to show the bug.
        Enable **incognito/private mode** to avoid interference from browser extensions.
        [Why reproductions are required?](https://antfu.me/posts/why-reproductions-are-required)
      placeholder: Valid link
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages`
      render: shell
      placeholder: System, JS/TS Runtime, Browser, NPM Packages
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Package Manager
      options:
        - pnpm
        - bun
        - npm
        - yarn
        - cnpm
        - other
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
