name: "\U0001F4A1 Feature Proposal"
description: Suggest new features for consideration
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thanks for your interest and taking the time to fill out this feature proposal!
        Please consider starring ⭐ to support our ongoing maintenance if you find it useful or your proposal was resolved afterwards 🆘
        > [!Tip]
        > [Open Source Software is served "as-is"](https://antfu.me/posts/why-reproductions-are-required#open-source-software-is-served-as-is), so please keep in mind that <a href="https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request"><img alt="PRs Welcome" src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGZpbGw9IiNmZmZmZmYiIGQ9Ik0xOS4wMSAxNS4xNjNWNy45OTdDMTkuMDA1IDYuMzkxIDE3LjkzMyA0IDE1IDRWMmwtNCAzbDQgM1Y2YzEuODI5IDAgMi4wMDEgMS41MzkgMi4wMSAydjcuMTYzYy0xLjQ0LjQzNC0yLjUgMS43NTctMi41IDMuMzM3YzAgMS45MyAxLjU3IDMuNSAzLjUgMy41czMuNS0xLjU3IDMuNS0zLjVjMC0xLjU4LTEuMDYtMi45MDMtMi41LTMuMzM3bS0xIDQuODM3Yy0uODI3IDAtMS41LS42NzMtMS41LTEuNXMuNjczLTEuNSAxLjUtMS41czEuNS42NzMgMS41IDEuNXMtLjY3MyAxLjUtMS41IDEuNU05LjUgNS41QzkuNSAzLjU3IDcuOTMgMiA2IDJTMi41IDMuNTcgMi41IDUuNWMwIDEuNTggMS4wNiAyLjkwMyAyLjUgMy4zMzd2Ni4zMjZjLTEuNDQuNDM0LTIuNSAxLjc1Ny0yLjUgMy4zMzdDMi41IDIwLjQzIDQuMDcgMjIgNiAyMnMzLjUtMS41NyAzLjUtMy41YzAtMS41OC0xLjA2LTIuOTAzLTIuNS0zLjMzN1Y4LjgzN0M4LjQ0IDguNDAzIDkuNSA3LjA4IDkuNSA1LjVtLTUgMEM0LjUgNC42NzMgNS4xNzMgNCA2IDRzMS41LjY3MyAxLjUgMS41UzYuODI3IDcgNiA3cy0xLjUtLjY3My0xLjUtMS41bTMgMTNjMCAuODI3LS42NzMgMS41LTEuNSAxLjVzLTEuNS0uNjczLTEuNS0xLjVTNS4xNzMgMTcgNiAxN3MxLjUuNjczIDEuNSAxLjUiLz48L3N2Zz4="></a>
        > ⚠️ Consensus should be reached through discussion first if the changes are significant
  - type: checkboxes
    attributes:
      label: "Before you start, please make sure to:"
      options:
      - label: Read the document
        required: true
      - label: Have tried the latest version
        required: true
      - label: Search to see if your proposal already exists
        required: true
      - label: Look for Q&A through appropriate channels like [Stack Overflow](https://stackoverflow.com/questions/ask) and [ChatGPT](https://chat.openai.com)
        required: false
  - type: markdown
    attributes:
      value: |
        > [!Caution]
        > Please ensure not to use this for unrelated purposes like consulting, otherwise it can be closed without further notice
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case, context, and rationale behind this feature proposal. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: proposed-API
    attributes:
      label: What does the proposed API look like?
      description: |
        Describe how you propose to solve the problem and provide code samples of how the API would work once implemented. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown) to format your code blocks
      placeholder: Assumed API
    validations:
      required: true
